name: "order_srv"
mode: "dev"
ip: "127.0.0.1"
rpcPort: 8385
httpPort: 8085
version: "v0.0.1"
start_time: "2022-06-01"
machine_id: 3

# 冒号后加空格
# 缩进是连续的两个空格
# 有兴趣的同学可以了解下toml
log:
  level: "debug"
  filename: "log/goods_srv.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "db1"
  max_open_conns: 100
  max_idle_conns: 10

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100

consul:
  addr: "127.0.0.1:8500"

goods_service:
  name: goods_srv

stock_service:
  name: stock_srv

rocketmq:
  addr: 192.168.110.145:9876
  group_id: order_srv
  topic:
    pay_timeout: xx_order_timeout
    stock_rollback: xx_stock_rollback
